end_time=2024-08-12T23:00:00Z,location=europe-west10,name=gcp-cluster,project_id=gcpdiag-gke-
cluster-autoscaler-rrrr,start_time=2024-08-12T01:00:00Z

gke/image-pull: Analysis and Resolution of Image Pull Failures on GKE clusters.

  This runbook investigates the gke cluster for Image pull failures and recommends remediation
  steps.

  Areas Examined:

  - GKE cluster

  - Stackdriver logs
    
[START]: Starting the image pull error diagnostics
[AUTOMATED STEP]: Check for "Failed to pull image.*not found" log entries.

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     Image cannot be pulled by a container on Pod, because the image is not found on the repository.
     Check if the image is correctly written or if it exists in the repository.
     Example log entry that would help identify involved objects:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     Follow the documentation:
     https://cloud.google.com/kubernetes-engine/docs/troubleshooting#ImagePullBackOff

[AUTOMATED STEP]: Check for "Failed to pull image.*403 Forbidden" log entries.

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     Image cannot be pulled by a container on Pod, because there are not enough permissions to pull it from the repository.
     Verify the node SA has the correct permissions.
     Example log entry that would help identify involved objects:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     Follow the documentation:
     https://cloud.google.com/artifact-registry/docs/integrate-gke#permissions

[AUTOMATED STEP]: Check for "Failed to pull image.*lookup.*server misbehaving" log entries.

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The DNS resolver (metadata server - 169.254.169.254:53) on the Node is unable to resolve the IP of the repository,
     preventing image pull. Check that the networking and DNS requirements mentioned in public documentation.
     Example log entry that would help identify involved objects:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     Follow the documentation:
     https://cloud.google.com/vpc/docs/configure-private-google-access#requirements

[AUTOMATED STEP]: Check for "Failed to pull image.*dial tcp.*199.36.153.\d:443: i/o timeout" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The connection from Node to restricted.googleapis.com (199.36.153.4/30) or private.googleapis.com (199.36.153.8/30) is
     timing out, preventing image pull. It is probable that a firewall rule is blocking this IP range. A firewall to permit
     this egress should be created.
     Example log entry that would help identify involved objects:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     Follow the documentation:
     https://cloud.google.com/vpc-service-controls/docs/set-up-private-connectivity

[AUTOMATED STEP]: Check for "Failed to pull image.*dial tcp.*i/o timeout" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The connection from Node to Google APIs is timing out. It is probable that a firewall rule is blocking this IP range.
     Expand results to see the blocked IP range.
     Example log entry that would help identify involved objects:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     Follow the documentation:
     https://cloud.google.com/kubernetes-engine/docs/concepts/firewall-rules

[AUTOMATED STEP]: Check for "Failed to pull image.*insufficient_scope" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     Either user or service account that's trying to pull the image doesn't have the necessary permissions to access it or
     Image doesn't exist.
     Example log entry that would help identify involved objects:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     1. Verify that the name of the image is correct.
     2. Follow the documentation:
     https://cloud.google.com/kubernetes-engine/docs/troubleshooting/deployed-workloads#image-not-found

[END]: Finalize `GKE Image Pull runbbok` diagnostics.


