{% block node_registration_checker_failure_reason %}
Node {node} in zone {location} is currently running, but it failed registration with kube-apiserver, below is the Node
Registration Checker summary:

{% for i in range(16) %}
{log_entries[{{ i }}]}
{% endfor %}
{% endblock node_registration_checker_failure_reason %}

{% block node_registration_checker_failure_reason_a1 %}
Node {node} in zone {location} failed registration with kube-apiserver, it is in a repair loop. Below is the Node
Registration Checker summary:

{% for i in range(16) %}
{log_entries[{{ i }}]}
{% endfor %}
{% endblock node_registration_checker_failure_reason_a1 %}

{% block node_registration_checker_failure_reason_a2 %}
Node {node} in zone {location} is not currently running. While checking logs it was found that it failed registration
with kube-apiserver. Below is the Node Registration Checker summary:

{% for i in range(16) %}
{log_entries[{{ i }}]}
{% endfor %}
{% endblock node_registration_checker_failure_reason_a2 %}

{% block node_registration_checker_failure_reason_a3 %}
Could not find summary from Node Registration Checker for node {node} in zone {location}. The node might have been
deleted before Node Registration Checker could finish running.
{% endblock node_registration_checker_failure_reason_a3 %}

{% block node_registration_checker_failure_remediation_a3 %}
Try to run the runbook with a node that is currently running.
{% endblock node_registration_checker_failure_remediation_a3 %}

{% block node_registration_checker_failure_remediation %}
To understand why the node failed registration with kube-apiserver, please check the following documentation page:
https://cloud.google.com/kubernetes-engine/docs/troubleshooting/node-registration#use-nrc
{% endblock node_registration_checker_failure_remediation %}

{% block node_registration_checker_success_reason %}
Node {node} is currently running and, according to the output from Node Registration Checker, it was registered
successfully. Below is the log entry that shows successful registration:

{log_entry}
{% endblock node_registration_checker_success_reason %}

{% block node_registration_checker_success_reason_a1 %}
Node {node} is not currently running, but according to the output from Node Registration Checker, it was registered
successfully in the past. Below is the log entry that shows successful registration:

{log_entry}
{% endblock node_registration_checker_success_reason_a1 %}

{% block node_registration_checker_uncertain_reason %}
The node {node} in the zone {location} is running, but there are no logs generated by Node Registration Checker in the
provided time range {start_time} - {end_time}.
{% endblock node_registration_checker_uncertain_reason %}

{% block node_registration_checker_uncertain_remediation %}
This runbook looks for logs generated by Node Registration Checker. Because there are no logs from Node Registration
Checker for the node {node}, but it is running, there could be a different issue with the node.
Please try the runbook with a different node in the same nodepool.
{% endblock node_registration_checker_uncertain_remediation %}

{% block node_insert_check_failure_reason %}
There were {NR_ERRORS} errors found for instances.insert method for nodepool {NODEPOOL} in the cluster {NAME} in
location {location} between {start_time} and {end_time}.
Below is the latest log entry found that can help you identify the issue and involved objects:

{log_entry}
{% endblock node_insert_check_failure_reason %}

{% block node_insert_check_failure_remediation %}
Please refer to the troubleshooting steps to learn how to resolve the errors:
https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-vm-creation
{% endblock node_insert_check_failure_remediation %}

{% block node_insert_check_success_reason %}
No errors found for instances.insert method for nodepool {NODEPOOL} in the cluster {NAME} in location {location} between
{start_time} and {end_time}.
{% endblock node_insert_check_success_reason %}
